services:
  - type: web
    name: buchu-shop-b
    runtime: node
    plan: free
    region: singapore
    branch: b-mall
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: SUPABASE_URL
        value: "https://pzhblcoszvkbnmolkkxf.supabase.co"
      - key: SUPABASE_ANON_KEY
        value: "sb_publishable_AT0jjmkKEHk3PJThm9aG1w_q2hSfV4y"
